import React, { createContext, useContext, useState } from 'react';

type Language = 'en' | 'it';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Hero
    hero_title: "Your Digital Government Portal",
    hero_subtitle: "Access all government services in one secure platform. From documents to appointments, we make bureaucracy simple.",
    get_started: "Get Started",
    
    // Features
    features_title: "One Platform, Multiple Services",
    features_subtitle: "Everything you need for government services, accessible anytime, anywhere",
    my_documents: "My Documents",
    my_documents_desc: "Access your ID, passport, residence permit, and all official documents digitally. No more printing or losing important papers.",
    appointments: "Appointments",
    appointments_desc: "Book and manage appointments with government offices. See availability in real-time and receive reminders.",
    news_updates: "News & Updates",
    news_updates_desc: "Stay informed about document status, local events, and civic opportunities in your community.",
    medical_records: "Medical Records",
    medical_records_desc: "Vaccination history, blood type, and medical background at your fingertips for emergencies and healthcare.",
    scholarships_benefits: "Scholarships & Benefits",
    scholarships_benefits_desc: "Discover scholarships, insurance programs, and social benefits you're eligible for.",
    emergency_info: "Emergency Information",
    emergency_info_desc: "Quick access to earthquake meeting points, emergency contacts, and safety resources in your area.",
    quick_access: "Quick Access",
    quick_access_desc: "Direct links to SPID, ANPR, INPS, PagoPA, and immigration services - all in one place.",
    civic_engagement: "Civic Engagement",
    civic_engagement_desc: "Participate in local democracy, view election information, and engage with your community.",
    
    // Dashboard
    dashboard_title: "Digital e-Ministero",
    profile: "Profile",
    view_profile: "View Profile",
    upload: "Upload",
    view: "View",
    book_new: "Book New",
    update: "Update",
    next_appointment: "Next Appointment",
    change_password: "Change Password",
    security_settings: "Security Settings",
    
    // Medical Records
    medical_records_title: "Medical Records",
    blood_type: "Blood Type",
    height: "Height",
    weight: "Weight",
    chronic_diseases: "Chronic Diseases",
    allergies: "Allergies",
    medications: "Medications",
    vaccinations: "Vaccinations",
    last_checkup: "Last Checkup",
    none: "None",
    cm: "cm",
    kg: "kg",
    
    // Appointment Booking
    book_appointment: "Book Questura Appointment",
    personal_info: "Personal Information",
    first_name: "First Name",
    last_name: "Last Name",
    location_details: "Location Details",
    region: "Region",
    province: "Province",
    comune: "Comune",
    select_region: "Select a region",
    select_province: "Select a province",
    select_comune: "Select a comune",
    appointment_details: "Appointment Details",
    questura: "Questura",
    select_questura: "Select Questura",
    service_type: "Service Type",
    select_service: "Select service type",
    preferred_date: "Preferred Date",
    time_slot: "Time Slot",
    select_time: "Select time slot",
    submit_request: "Submit Request",
    appointment_confirmed: "Appointment Request Submitted",
    appointment_confirmation_message: "Your appointment request has been submitted successfully. You will receive a confirmation shortly.",
    available_appointments: "Available Appointments",
    available_slots: "Available slots",
    
    // Scholarships
    scholarships_title: "Scholarships & Benefits",
    education_level: "Education Level",
    high_school: "High School",
    university: "University",
    your_age: "Your Age",
    filter_results: "Filter Results",
    available_scholarships: "Available Scholarships",
    eligibility: "Eligibility",
    amount: "Amount",
    deadline: "Deadline",
    apply_now: "Apply Now",
    
    // Emergency
    emergency_title: "Emergency Information",
    nearest_meeting_points: "Nearest Earthquake Meeting Points",
    emergency_contacts: "Emergency Contacts",
    minutes_away: "minutes away",
    police: "Police (Carabinieri)",
    ambulance: "Ambulance",
    fire_department: "Fire Department",
    coast_guard: "Coast Guard",
    
    // Quick Access
    quick_access_title: "Quick Access Links",
    spid_desc: "Digital Identity System",
    anpr_desc: "National Registry",
    inps_desc: "Social Security",
    pagopa_desc: "Government Payments",
    immigration_desc: "Immigration Services",
    
    // Civic Engagement
    civic_title: "Civic Engagement",
    select_location: "Select Your Location",
    city: "City",
    select_city: "Select a city",
    recent_elections: "Recent Elections (Last 2 Years)",
    election_type: "Election Type",
    winner: "Winner",
    vote_percentage: "Vote Percentage",
    other_candidates: "Other Candidates",
    upcoming_elections: "Upcoming Elections",
    no_upcoming: "No upcoming elections scheduled",
    your_polling_station: "Your Polling Station",
    contact_authorities: "Contact Local Authorities",
    subject: "Subject",
    message: "Message",
    send_message: "Send Message",
    
    // Footer
    about: "About",
    privacy: "Privacy Policy",
    terms: "Terms of Service",
    contact: "Contact",
    all_rights: "All rights reserved",
    my_profile: "My Profile",
    contact_us: "Contact Us",
    phone: "Phone",
    address: "Address",
    name: "Name",
    voice_listening: "Voice Listening Active",
    all_rights_reserved: "All rights reserved",
    logout: "Logout",
    
    // Authentication
    auth_title: "Welcome to CivicLink",
    auth_subtitle: "Sign in to access all services",
    codice_fiscale: "Codice Fiscale",
    codice_fiscale_hint: "Enter any number for testing purposes",
    login_with_spid: "Login with SPID",
    cie_description: "Place your ID card near your device to authenticate",
    authenticate_cie: "Authenticate with CIE",
    cns_description: "Insert your smart card to authenticate",
    authenticate_cns: "Authenticate with CNS",
    no_digital_auth: "Don't have digital authentication?",
    document_verification: "Document Verification",
    upload_document: "Upload Identity Document",
    enter_codice_fiscale: "Enter your Codice Fiscale",
    verify_submit: "Verify & Submit",
    back_to_home: "Back to Home",
    login_success: "Login Successful",
    welcome_message: "Welcome to CivicLink!",
    cie_auth: "CIE Authentication",
    cie_instruction: "Simulating NFC authentication...",
    cns_auth: "CNS Authentication",
    cns_instruction: "Simulating smart card authentication...",
    
    // Security Settings
    current_password: "Current Password",
    new_password: "New Password",
    confirm_password: "Confirm New Password",
    enter_current_password: "Enter your current password",
    enter_new_password: "Enter new password",
    enter_password_again: "Enter password again",
    password_requirements: "Password must be at least 8 characters",
    update_password: "Update Password",
    change_password_description: "Update your password to keep your account secure",
    error: "Error",
    success: "Success",
    passwords_dont_match: "Passwords don't match",
    password_too_short: "Password must be at least 8 characters",
    password_updated: "Password updated successfully",
    
    // Residence Permit
    residence_permit: "Residence Permit",
    date_of_birth: "Date of Birth",
    place_of_birth: "Place of Birth",
    nationality: "Nationality",
    gender: "Gender",
    permit_type: "Permit Type",
    permit_number: "Permit Number",
    issue_date: "Issue Date",
    expiry_date: "Expiry Date",
    issued_by: "Issued By",
    residence_address: "Residence Address",
    permit_valid_note: "This document must be carried together with a valid passport",
    
    // News & Updates
    news_subtitle: "Latest updates from Macerata, Italy",
    news_1_title: "New Digital Residence Permit Processing",
    news_1_desc: "Questura di Macerata has launched a new digital system for faster residence permit processing. Average wait time reduced to 30 days.",
    news_2_title: "Community Integration Workshop",
    news_2_desc: "Free Italian language and integration workshops starting next month. Register at the Comune di Macerata.",
    news_3_title: "Volunteer Opportunities Available",
    news_3_desc: "Join local community service programs. Volunteering counts toward citizenship requirements.",
    news_4_title: "Simplified Document Renewal Process",
    news_4_desc: "The permit renewal process is now entirely online. No physical visit required for most cases.",
    news_5_title: "Municipal Budget Consultation Open",
    news_5_desc: "Residents can now provide input on the 2026 municipal budget. Public forum on November 15th.",
    document_status: "Document Status",
    local_events: "Local Events",
    civic_opportunities: "Civic Opportunities",
    
    // Profile Box
    profile_phone: "Phone",
    profile_email: "Email",
    profile_name: "Name",
    profile_fiscal: "Codice Fiscale",
    profile_address: "Address",
    
    // FAQ
    faq_title: "❓ Frequently Asked Questions",
    faq_subtitle: "Find answers to common questions about e-Ministero",
    faq_devices_question: "📱 Which devices does e-Ministero work on?",
    faq_devices_answer: "Currently, e-Ministero is available as a website accessible from any modern web browser on desktop, tablet, or mobile devices.",
    faq_support_question: "🛠️ How can I contact technical support?",
    faq_support_answer: "Email: support@e-ministero.it\nPhone: +39 0733 234567\nLocation: Macerata, Italy",
    faq_vaccination_question: "💉 What should I do if my vaccination information is not up to date?",
    faq_vaccination_answer: "You can update your vaccination records by clicking the edit button in the Medical Records section.",
    faq_scholarship_question: "🎓 How do I track my scholarship and social assistance applications?",
    faq_scholarship_answer: "If your applications are connected to our system, you can view their status in the 'Scholarship & Social Assistance Results' section on the website.",
    more_questions: "Have more questions?",
    contact_support: "Feel free to reach out to our support team!",
    
    // How It Works
    how_title: "How It Works",
    how_subtitle: "Simple steps to access all government services",
    how_step1_title: "Create Account",
    how_step1_desc: "Register with your SPID or create a new account",
    how_step2_title: "Access Services",
    how_step2_desc: "Browse and access all available government services",
    how_step3_title: "Get Notifications",
    how_step3_desc: "Receive updates about your applications and documents",
    how_step4_title: "Complete Tasks",
    how_step4_desc: "Manage everything from one convenient platform",
    
    // Pending Transactions
    pending_title: "Pending Transactions",
    pending_subtitle: "Tasks that require your attention",
    pending_scholarship_title: "Scholarship Application - Additional Documents Required",
    pending_scholarship_desc: "Please submit proof of enrollment to complete your scholarship application.",
    pending_assistance_title: "Social Assistance Application - Under Review",
    pending_assistance_desc: "Your application is being reviewed. Expected response time: 5-7 business days.",
    badge_action_required: "Action Required",
    badge_waiting: "Waiting",
    pending_view_details: "View Details",
    pending_empty: "No pending transactions at this time",
    
    // Scholarship Results
    scholarship_results_title: "Scholarship & Social Assistance Results",
    scholarship_results_subtitle: "View the status of your applications",
    scholarship_university_title: "University Scholarship 2024",
    scholarship_assistance_title: "Family Social Assistance",
    status_approved: "Approved",
    status_rejected: "Rejected",
    status_pending: "Pending",
    applied_on: "Applied on",
    view_details: "View Details",
    scholarship_empty: "No applications found",
  },
  it: {
    // Hero
    hero_title: "Il Tuo Portale Governativo Digitale",
    hero_subtitle: "Accedi a tutti i servizi governativi in un'unica piattaforma sicura. Dai documenti agli appuntamenti, rendiamo la burocrazia semplice.",
    get_started: "Inizia",
    
    // Features
    features_title: "Una Piattaforma, Molteplici Servizi",
    features_subtitle: "Tutto ciò di cui hai bisogno per i servizi governativi, accessibile sempre e ovunque",
    my_documents: "I Miei Documenti",
    my_documents_desc: "Accedi alla tua carta d'identità, passaporto, permesso di soggiorno e tutti i documenti ufficiali in formato digitale. Basta stampare o perdere documenti importanti.",
    appointments: "Appuntamenti",
    appointments_desc: "Prenota e gestisci appuntamenti con gli uffici governativi. Visualizza la disponibilità in tempo reale e ricevi promemoria.",
    news_updates: "Notizie e Aggiornamenti",
    news_updates_desc: "Rimani informato sullo stato dei documenti, eventi locali e opportunità civiche nella tua comunità.",
    medical_records: "Cartella Clinica",
    medical_records_desc: "Storico vaccinazioni, gruppo sanguigno e informazioni mediche a portata di mano per emergenze e assistenza sanitaria.",
    scholarships_benefits: "Borse di Studio e Benefici",
    scholarships_benefits_desc: "Scopri borse di studio, programmi assicurativi e benefici sociali per cui sei idoneo.",
    emergency_info: "Informazioni di Emergenza",
    emergency_info_desc: "Accesso rapido ai punti di incontro per terremoti, contatti di emergenza e risorse di sicurezza nella tua zona.",
    quick_access: "Accesso Rapido",
    quick_access_desc: "Collegamenti diretti a SPID, ANPR, INPS, PagoPA e servizi immigrazione - tutto in un unico posto.",
    civic_engagement: "Partecipazione Civica",
    civic_engagement_desc: "Partecipa alla democrazia locale, visualizza informazioni elettorali e interagisci con la tua comunità.",
    
    // Dashboard
    dashboard_title: "e-Ministero Digitale",
    profile: "Profilo",
    view_profile: "Visualizza Profilo",
    upload: "Carica",
    view: "Visualizza",
    book_new: "Prenota Nuovo",
    update: "Aggiorna",
    next_appointment: "Prossimo Appuntamento",
    change_password: "Cambia Password",
    security_settings: "Impostazioni di Sicurezza",
    
    // Medical Records
    medical_records_title: "Cartella Clinica",
    blood_type: "Gruppo Sanguigno",
    height: "Altezza",
    weight: "Peso",
    chronic_diseases: "Malattie Croniche",
    allergies: "Allergie",
    medications: "Farmaci",
    vaccinations: "Vaccinazioni",
    last_checkup: "Ultimo Controllo",
    none: "Nessuno",
    cm: "cm",
    kg: "kg",
    
    // Appointment Booking
    book_appointment: "Prenota Appuntamento Questura",
    personal_info: "Informazioni Personali",
    first_name: "Nome",
    last_name: "Cognome",
    location_details: "Dettagli Località",
    region: "Regione",
    province: "Provincia",
    comune: "Comune",
    select_region: "Seleziona una regione",
    select_province: "Seleziona una provincia",
    select_comune: "Seleziona un comune",
    appointment_details: "Dettagli Appuntamento",
    questura: "Questura",
    select_questura: "Seleziona Questura",
    service_type: "Tipo di Servizio",
    select_service: "Seleziona tipo di servizio",
    preferred_date: "Data Preferita",
    time_slot: "Fascia Oraria",
    select_time: "Seleziona fascia oraria",
    submit_request: "Invia Richiesta",
    appointment_confirmed: "Richiesta Appuntamento Inviata",
    appointment_confirmation_message: "La tua richiesta di appuntamento è stata inviata con successo. Riceverai una conferma a breve.",
    available_appointments: "Appuntamenti Disponibili",
    available_slots: "Posti disponibili",
    
    // Scholarships
    scholarships_title: "Borse di Studio e Benefici",
    education_level: "Livello di Istruzione",
    high_school: "Scuola Superiore",
    university: "Università",
    your_age: "La Tua Età",
    filter_results: "Filtra Risultati",
    available_scholarships: "Borse di Studio Disponibili",
    eligibility: "Requisiti",
    amount: "Importo",
    deadline: "Scadenza",
    apply_now: "Candidati Ora",
    
    // Emergency
    emergency_title: "Informazioni di Emergenza",
    nearest_meeting_points: "Punti di Incontro Terremoto Più Vicini",
    emergency_contacts: "Contatti di Emergenza",
    minutes_away: "minuti di distanza",
    police: "Polizia (Carabinieri)",
    ambulance: "Ambulanza",
    fire_department: "Vigili del Fuoco",
    coast_guard: "Guardia Costiera",
    
    // Quick Access
    quick_access_title: "Collegamenti Rapidi",
    spid_desc: "Sistema di Identità Digitale",
    anpr_desc: "Anagrafe Nazionale",
    inps_desc: "Previdenza Sociale",
    pagopa_desc: "Pagamenti Governativi",
    immigration_desc: "Servizi Immigrazione",
    
    // Civic Engagement
    civic_title: "Partecipazione Civica",
    select_location: "Seleziona la Tua Località",
    city: "Città",
    select_city: "Seleziona una città",
    recent_elections: "Elezioni Recenti (Ultimi 2 Anni)",
    election_type: "Tipo di Elezione",
    winner: "Vincitore",
    vote_percentage: "Percentuale Voti",
    other_candidates: "Altri Candidati",
    upcoming_elections: "Prossime Elezioni",
    no_upcoming: "Nessuna elezione programmata",
    your_polling_station: "Il Tuo Seggio Elettorale",
    contact_authorities: "Contatta le Autorità Locali",
    subject: "Oggetto",
    message: "Messaggio",
    send_message: "Invia Messaggio",
    
    // Footer
    about: "Chi Siamo",
    privacy: "Privacy Policy",
    terms: "Termini di Servizio",
    contact: "Contatti",
    all_rights: "Tutti i diritti riservati",
    my_profile: "Il Mio Profilo",
    contact_us: "Contattaci",
    phone: "Telefono",
    address: "Indirizzo",
    name: "Nome",
    voice_listening: "Ascolto Vocale Attivo",
    all_rights_reserved: "Tutti i diritti riservati",
    logout: "Disconnetti",
    
    // Authentication
    auth_title: "Benvenuto a CivicLink",
    auth_subtitle: "Accedi per utilizzare tutti i servizi",
    codice_fiscale: "Codice Fiscale",
    codice_fiscale_hint: "Inserisci qualsiasi numero per test",
    login_with_spid: "Accedi con SPID",
    cie_description: "Avvicina la tua carta d'identità al dispositivo per autenticarti",
    authenticate_cie: "Autentica con CIE",
    cns_description: "Inserisci la tua smart card per autenticarti",
    authenticate_cns: "Autentica con CNS",
    no_digital_auth: "Non hai l'autenticazione digitale?",
    document_verification: "Verifica Documenti",
    upload_document: "Carica Documento d'Identità",
    enter_codice_fiscale: "Inserisci il tuo Codice Fiscale",
    verify_submit: "Verifica e Invia",
    back_to_home: "Torna alla Home",
    login_success: "Accesso Riuscito",
    welcome_message: "Benvenuto su CivicLink!",
    cie_auth: "Autenticazione CIE",
    cie_instruction: "Simulazione autenticazione NFC...",
    cns_auth: "Autenticazione CNS",
    cns_instruction: "Simulazione autenticazione smart card...",
    
    // Security Settings
    current_password: "Password Attuale",
    new_password: "Nuova Password",
    confirm_password: "Conferma Nuova Password",
    enter_current_password: "Inserisci la tua password attuale",
    enter_new_password: "Inserisci nuova password",
    enter_password_again: "Inserisci di nuovo la password",
    password_requirements: "La password deve contenere almeno 8 caratteri",
    update_password: "Aggiorna Password",
    change_password_description: "Aggiorna la tua password per mantenere sicuro il tuo account",
    error: "Errore",
    success: "Successo",
    passwords_dont_match: "Le password non corrispondono",
    password_too_short: "La password deve contenere almeno 8 caratteri",
    password_updated: "Password aggiornata con successo",
    
    // Residence Permit
    residence_permit: "Permesso di Soggiorno",
    date_of_birth: "Data di Nascita",
    place_of_birth: "Luogo di Nascita",
    nationality: "Nazionalità",
    gender: "Sesso",
    permit_type: "Tipo di Permesso",
    permit_number: "Numero Permesso",
    issue_date: "Data di Rilascio",
    expiry_date: "Data di Scadenza",
    issued_by: "Rilasciato da",
    residence_address: "Indirizzo di Residenza",
    permit_valid_note: "Questo documento deve essere portato insieme a un passaporto valido",
    
    // News & Updates
    news_subtitle: "Ultimi aggiornamenti da Macerata, Italia",
    news_1_title: "Nuovo Processo Digitale per Permessi di Soggiorno",
    news_1_desc: "La Questura di Macerata ha lanciato un nuovo sistema digitale per un'elaborazione più rapida dei permessi. Tempo medio ridotto a 30 giorni.",
    news_2_title: "Workshop di Integrazione Comunitaria",
    news_2_desc: "Corsi gratuiti di lingua italiana e integrazione dal prossimo mese. Iscriviti al Comune di Macerata.",
    news_3_title: "Opportunità di Volontariato Disponibili",
    news_3_desc: "Unisciti ai programmi di servizio comunitario locale. Il volontariato conta per i requisiti di cittadinanza.",
    news_4_title: "Processo Semplificato di Rinnovo Documenti",
    news_4_desc: "Il processo di rinnovo del permesso è ora interamente online. Nessuna visita fisica richiesta nella maggior parte dei casi.",
    news_5_title: "Consultazione Bilancio Comunale Aperta",
    news_5_desc: "I residenti possono ora fornire input sul bilancio comunale 2026. Forum pubblico il 15 novembre.",
    document_status: "Stato Documento",
    local_events: "Eventi Locali",
    civic_opportunities: "Opportunità Civiche",
    
    // Profile Box
    profile_phone: "Telefono",
    profile_email: "Email",
    profile_name: "Nome",
    profile_fiscal: "Codice Fiscale",
    profile_address: "Indirizzo",
    
    // FAQ
    faq_title: "❓ Domande Frequenti",
    faq_subtitle: "Trova risposte alle domande comuni su e-Ministero",
    faq_devices_question: "📱 Su quali dispositivi funziona e-Ministero?",
    faq_devices_answer: "Attualmente, e-Ministero è disponibile come sito web accessibile da qualsiasi browser moderno su desktop, tablet o dispositivi mobili.",
    faq_support_question: "🛠️ Come posso contattare il supporto tecnico?",
    faq_support_answer: "Email: support@e-ministero.it\nTelefono: +39 0733 234567\nLocalità: Macerata, Italia",
    faq_vaccination_question: "💉 Cosa devo fare se le mie informazioni sulla vaccinazione non sono aggiornate?",
    faq_vaccination_answer: "Puoi aggiornare i tuoi record di vaccinazione facendo clic sul pulsante modifica nella sezione Cartelle Cliniche.",
    faq_scholarship_question: "🎓 Come posso tenere traccia delle mie domande di borsa di studio e assistenza sociale?",
    faq_scholarship_answer: "Se le tue domande sono collegate al nostro sistema, puoi visualizzarne lo stato nella sezione 'Risultati Borse di Studio e Assistenza Sociale' sul sito web.",
    more_questions: "Hai altre domande?",
    contact_support: "Non esitare a contattare il nostro team di supporto!",
    
    // How It Works
    how_title: "Come Funziona",
    how_subtitle: "Semplici passaggi per accedere a tutti i servizi governativi",
    how_step1_title: "Crea Account",
    how_step1_desc: "Registrati con il tuo SPID o crea un nuovo account",
    how_step2_title: "Accedi ai Servizi",
    how_step2_desc: "Sfoglia e accedi a tutti i servizi governativi disponibili",
    how_step3_title: "Ricevi Notifiche",
    how_step3_desc: "Ricevi aggiornamenti sulle tue domande e documenti",
    how_step4_title: "Completa le Attività",
    how_step4_desc: "Gestisci tutto da un'unica piattaforma conveniente",
    
    // Pending Transactions
    pending_title: "Transazioni in Sospeso",
    pending_subtitle: "Attività che richiedono la tua attenzione",
    pending_scholarship_title: "Domanda di Borsa di Studio - Documenti Aggiuntivi Richiesti",
    pending_scholarship_desc: "Si prega di presentare la prova di iscrizione per completare la domanda di borsa di studio.",
    pending_assistance_title: "Domanda di Assistenza Sociale - In Revisione",
    pending_assistance_desc: "La tua domanda è in fase di revisione. Tempo di risposta previsto: 5-7 giorni lavorativi.",
    badge_action_required: "Azione Richiesta",
    badge_waiting: "In Attesa",
    pending_view_details: "Visualizza Dettagli",
    pending_empty: "Nessuna transazione in sospeso al momento",
    
    // Scholarship Results
    scholarship_results_title: "Risultati Borse di Studio e Assistenza Sociale",
    scholarship_results_subtitle: "Visualizza lo stato delle tue domande",
    scholarship_university_title: "Borsa di Studio Universitaria 2024",
    scholarship_assistance_title: "Assistenza Sociale Familiare",
    status_approved: "Approvato",
    status_rejected: "Rifiutato",
    status_pending: "In Attesa",
    applied_on: "Richiesta il",
    view_details: "Visualizza Dettagli",
    scholarship_empty: "Nessuna domanda trovata",
  },
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
